### ISSUE TITLE
Error when function arg is a function

### ISSUE THREAD

**Issue by awvalenti** [Farenheith/sinon-chai-calls-assertion#8]
```javascript
const s = sinon.spy()
s(0)
expect(s).to.have.callsLike([''])
```
is fine, but

```javascript
const s = sinon.spy()
s(() => 0)
expect(s).to.have.callsLike([''])
```
causes `TypeError: Cannot read property 'replace' of undefined`

**Comment by Farenheith** [comment]
Hello, @awvalenti again, I'm really sorry for the late reply, I wasn't monitoring this project.
This error has been fixed on https://github.com/Codibre/chai-callslike, the new name of this package.

Thank you
